<?php 

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class AvailableZipCodes {
	private $available_zip_codes_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'available_zip_codes_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'available_zip_codes_page_init' ) );
	}

	public function available_zip_codes_add_plugin_page() {
		add_menu_page(
			'Zip Codes', // page_title
			'Zip Codes', // menu_title
			'manage_options', // capability
			'available-zip-codes', // menu_slug
			array( $this, 'available_zip_codes_create_admin_page' ), // function
			'dashicons-location', // icon_url
			75 // position
		);
	}

	public function available_zip_codes_create_admin_page() {
		$this->available_zip_codes_options = get_option( 'available_zip_codes_option_name' ); ?>

		<div class="wrap">
			<h2>Zip Codes</h2>
			<p>Here are the Zip Codes you can currently work in.</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'available_zip_codes_option_group' );
					do_settings_sections( 'available-zip-codes-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function available_zip_codes_page_init() {
		register_setting(
			'available_zip_codes_option_group', // option_group
			'available_zip_codes_option_name', // option_name
			array( $this, 'available_zip_codes_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'available_zip_codes_setting_section', // id
			'Settings', // title
			array( $this, 'available_zip_codes_section_info' ), // callback
			'available-zip-codes-admin' // page
		);

		add_settings_field(
			'zip_codes_0', // id
			'Zip Codes', // title
			array( $this, 'zip_codes_0_callback' ), // callback
			'available-zip-codes-admin', // page
			'available_zip_codes_setting_section' // section
		);
	}

	public function available_zip_codes_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['zip_codes_0'] ) ) {
			$sanitary_values['zip_codes_0'] = esc_textarea( $input['zip_codes_0'] );
		}

		return $sanitary_values;
	}

	public function available_zip_codes_section_info() {
		
	}

	public function zip_codes_0_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="available_zip_codes_option_name[zip_codes_0]" id="zip_codes_0">%s</textarea>',
			isset( $this->available_zip_codes_options['zip_codes_0'] ) ? esc_attr( $this->available_zip_codes_options['zip_codes_0']) : ''
		);
	}

}
if ( is_admin() )
	$available_zip_codes = new AvailableZipCodes();

/* 
 * Retrieve this value with:
 * $available_zip_codes_options = get_option( 'available_zip_codes_option_name' ); // Array of All Options
 * $zip_codes_0 = $available_zip_codes_options['zip_codes_0']; // Zip Codes
 */
